const normalize = (value: string) => value.trim().toLowerCase();

export const CATEGORY_DEFINITIONS = [
  {
    id: 'fresh',
    title: 'Fruits & Vegetables',
    keywords: [
      'tomato',
      'onion',
      'potato',
      'banana',
      'apple',
      'mango',
      'orange',
      'pomegranate',
      'papaya',
      'grapes',
      'guava',
      'spinach',
      'palak',
      'methi',
      'garlic',
      'ginger',
      'green chilli',
      'coriander leaves',
      'curry leaves',
      'cauliflower',
      'brinjal',
      'cabbage',
      'capsicum',
      'beans',
      'carrot',
    ],
  },
  {
    id: 'atta',
    title: 'Atta, Rice & Dal',
    keywords: [
      'atta',
      'flour',
      'maida',
      'suji',
      'rava',
      'besan',
      'multigrain',
      'rice',
      'basmati',
      'sona',
      'kolam',
      'brown rice',
      'idli rice',
      'broken rice',
      'jowar',
      'bajra',
      'ragi',
      'millet',
      'dal',
      'lentil',
      'toor',
      'urad',
      'moong',
      'masoor',
      'chana',
      'rajma',
      'kabuli',
      'kala',
      'lobia',
      'matki',
    ],
  },
  {
    id: 'dairy',
    title: 'Dairy & Breakfast',
    keywords: [
      'milk',
      'curd',
      'dahi',
      'paneer',
      'cheese',
      'butter',
      'cream',
      'buttermilk',
      'bread',
      'egg',
      'eggs',
    ],
  },
  {
    id: 'masala',
    title: 'Masala, Oil & Pantry',
    keywords: [
      'masala',
      'spice',
      'whole spices',
      'mirchi',
      'chilli',
      'turmeric',
      'haldi',
      'cumin',
      'jeera',
      'coriander powder',
      'bay leaf',
      'cinnamon',
      'clove',
      'cardamom',
      'pepper',
      'fennel',
      'fenugreek',
      'hing',
      'mustard seeds',
      'oil',
      'ghee',
      'salt',
      'sugar',
      'jaggery',
    ],
  },
  {
    id: 'snacks',
    title: 'Snacks & Beverages',
    keywords: [
      'namkeen',
      'chips',
      'biscuit',
      'cookie',
      'noodles',
      'maggi',
      'pasta',
      'vermicelli',
      'pickles',
      'papad',
      'sauce',
      'ready-to-eat',
      'oats',
      'cornflakes',
      'dry fruits',
      'peanuts',
      'makhana',
      'chocolate',
      'tea',
      'coffee',
      'juice',
      'soda',
    ],
  },
  {
    id: 'meat',
    title: 'Meat, Fish & Eggs',
    keywords: ['chicken', 'mutton', 'fish', 'prawn', 'egg', 'eggs'],
  },
  {
    id: 'home',
    title: 'Household Essentials',
    keywords: ['detergent', 'soap', 'shampoo', 'cleaner', 'tissue', 'foil'],
  },
] as const;

export const OTHER_CATEGORY = {
  id: 'other',
  title: 'Other Essentials',
  keywords: [] as string[],
};

export const CATEGORY_SECTIONS = [...CATEGORY_DEFINITIONS, OTHER_CATEGORY];

export const getCategoryId = (name: string) => {
  const normalized = normalize(name);
  const match = CATEGORY_DEFINITIONS.find((category) =>
    category.keywords.some((keyword) => normalized.includes(keyword))
  );
  return match?.id ?? OTHER_CATEGORY.id;
};
